import turtle as t
import math as m
import time
s=t.Screen()
s.setup(700, 700)
s.bgcolor("black")
s.tracer(0)
p=t.Turtle()
p.hideturtle()
p.pencolor("white")
R=260
r=R/ m.sqrt(3)
num_arms=6
layers_per_arm =28
for k in range(num_arms):
    a_tip= m.radians(k*60)
    a_left= m.radians(k*60-30)
    a_right= m.radians(k*60+30)
    p_tip_x= R*m.cos(a_tip)
    p_tip_y= R*m.sin(a_tip)
    p_left_x= r*m.cos(a_left)
    p_left_y= r*m.sin(a_left)
    p_right_x= r*m.cos(a_right)
    p_right_y= r*m.sin(a_right)
    p_tip=(p_tip_x, p_tip_y)
    p_left=(p_left_x, p_left_y)
    p_right=(p_right_x, p_right_y)
    p.width(2.8)
    p.penup()
    p.goto(0, 0)
    p.pendown()
    p.goto(p_left)
    p.goto(p_tip)
    p.goto(p_right)
    p.goto(0, 0)
    p.goto(p_tip)
    s.update()
    time.sleep(0.08)
    p.width(1.5)
    for i in range(layers_per_arm, 0, -1):
        ratio= i/layers_per_arm
        L_x=p_left[0] + ratio*(p_tip[0]-p_left[0])
        L_y=p_left[1] + ratio*(p_tip[1]-p_left[1])
        R_x=p_right[0] + ratio*(p_tip[0]-p_right[0])
        R_y=p_right[1] + ratio*(p_tip[1]-p_right[1])
        L_pt=(L_x, L_y)
        R_pt=(R_x, R_y)
        V_L=(ratio * p_left[0], ratio * p_left[1])
        V_R=(ratio * p_right[0], ratio * p_right[1])
        p.penup()
        p.goto(V_L)
        p.pendown()
        p.goto(L_pt)
        p.goto(R_pt)
        p.goto(V_R)
        s.update()
        time.sleep(0.015)

t.done()
